bi_lms/applications/usuario/urls.py
from django.urls import path
from .import views

app_name='usuario_app'

urlpatterns = [
    path('home/',views.home.as_view(), name="Home"),
    path('login/',views.Login.as_view(), name='login'),
    path('logout/',views.Logout.as_view(), name='logout'),
    path('cambiarpass/',views.UpdatePass.as_view(), name='cambiarpass'),
]

bi_lms/bi_lms/urls.py
from django.contrib import admin,auth
from django.urls import path, include
from applications.usuario import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('applications.usuario.urls')),
]

bi_lms/applications/organizacion/models.py
from django.db import models

# Create your models here.

class Organizacion(models.Model):
 
    delegacion = models.CharField("Delegación",max_length=20)
    grupo = models.CharField("Grupo",max_length=25)
    servicio = models.CharField("Servicio",max_length=20)
    
    class Meta:
        verbose_name='Organizacion'
        verbose_name_plural='Organizaciones'
        # Para ordenar por los campos seleccionados

        ordering=['delegacion','grupo']
        
        # si quisieramos descendente colocamos el signo "-" en el campo correspondiente
        
        # ordering=['-delegacion','grupo']
        
        # Para no permitir que se registren campos coincidentes
        
        unique_together=('delegacion','grupo','servicio')
    
    def __str__(self):
        return self.servicio

  

bi_lms/applications/usuario/models.py
from django.db import models
from ckeditor.fields import RichTextField



class Skill(models.Model):
    skill = models.CharField("Logros", max_length=50)
    
    def __str__(self):
        return self.skill
    
    class Meta:
        verbose_name='Logro'
        verbose_name_plural='Logros'
        # Para ordenar por los campos seleccionados

        ordering=['skill']
    
    
class Usuario(models.Model):
    cod_gestor = models.CharField("Usuario", max_length=7, unique=True,default="")
    nombre = models.CharField("Nombre", max_length=20,default="")
    primer_ap = models.CharField("Primer apellido", max_length=20,default="")
    segundo_ap = models.CharField("Segundo apellido", max_length=20,default="")
    # nombre_completo = models.CharField("Nombre Completo", max_length=40,blank=True)
    email=models.EmailField("Email",blank=True, null=True)
    extension=models.IntegerField(default=0)
    job=models.CharField("Función",max_length=30,blank=True, null=True)
    delegacion=models.CharField("Delegación",max_length=30,blank=False, null=False,default="")
    grupo_titular=models.CharField("Grupo",max_length=30,blank=False, null=False,default="")
    servicio_titular=models.CharField("Servicio",max_length=30,blank=False, null=False,default="")
    # grupo_refuerzo=models.CharField(max_length=30,blank=True, null=True)
    # servicio_refuerzo_1=models.CharField(max_length=30,blank=True, null=True)
    # servicio_refuerzo_2=models.CharField(max_length=30,blank=True, null=True)
    # fecha_nacimiento=models.DateField()
    # fecha_incorporacion=models.DateField()
    # discapacidad=models.CharField(max_length=2)
    # reduccion_jornada=models.CharField(max_length=2)
    # horas_jornada=models.IntegerField()
    # imagen=models.ImageField(upload_to="gestion_usuarios", null=True, blank=True)
    skill = models.ManyToManyField(Skill)
    comentarios=RichTextField(blank=True, null=True,default="")
    USERNAME_FIELD='username'
    # objects=UserManager()
    
    def __str__(self):
        return self.cod_gestor

bi_lms/applications/usuario/forms.py
from django import forms
from django.contrib.auth import authenticate
from .models import Usuario



class LoginForm(forms.Form):
    username=forms.CharField(
        label='Usuario',
        required=True,
        widget=forms.TextInput(
            attrs={'placeholder':'Usuario'}
        )
    )
        
    password=forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={'placeholder':'Contraseña'}
        )
    )
  
    
    def clean(self):
        cleaned_data=super(LoginForm,self).clean()
        username=self.cleaned_data['username']
        password=self.cleaned_data['password']
        
        if not authenticate(username=username,password=password):
            raise forms.ValidationError('Los datos de usuario no son correctos')
        
        return self.cleaned_data
    

class UpdatePassForm(forms.Form):
    password1=forms.CharField(
        label='',
        required=True,
        widget=forms.PasswordInput(
            attrs={'placeholder':'Contraseña Actual'}
        )
    )
    
    password2=forms.CharField(
        label='',
        required=True,
        widget=forms.PasswordInput(
            attrs={'placeholder':'Contraseña Nueva'}
        )
    )
    password3=forms.CharField(
        label='',
        required=True,
        widget=forms.PasswordInput(
            attrs={'placeholder':'Confirmar Contraseña'}
        )
    )
    def clean(self):
        cleaned_data=super(UpdatePassForm,self).clean()
        username1=self.cleaned_data['password2']
        username2=self.cleaned_data['password3']
        
        if not (username1==username2):
            raise forms.ValidationError('Las contraseñas proporcionadas no coinciden, por favor, vuelve a intentarlo')
        
        return self.cleaned_data

bi_lms/applications/organizacion/views.py
from django.shortcuts import render

# Create your views here.

bi_lms/applications/usuario/views.py
from django.shortcuts import render, HttpResponse
from django.views.generic.edit import (FormView)
from django.urls import reverse_lazy, reverse
from .forms import LoginForm, UpdatePassForm
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.views.generic import (View,TemplateView)
from .models import Usuario
# Create your views here.



class home(LoginRequiredMixin, TemplateView):
    template_name = "usuario/home.html"
    # a donde redirigir en caso de que no este logado
    login_url=reverse_lazy('usuario_app:login')



class Login(FormView):
    template_name='usuario/login.html'
    form_class=LoginForm
    success_url=reverse_lazy('usuario_app:Home')
    
    def form_valid(self,form):
        user=authenticate(
            username=form.cleaned_data['username'],
            password=form.cleaned_data['password'],
        )
        login(self.request,user)
        return super(Login,self).form_valid(form)
    

    
class Logout(View):
    
    def get(self,request,*args,**kargs):
        logout(request)
        return HttpResponseRedirect(
            reverse('usuario_app:login')
        )
        
    
class UpdatePass(LoginRequiredMixin, FormView):
    template_name='usuario/cambiar_pass.html'
    form_class=UpdatePassForm
    success_url=reverse_lazy('usuario_app:login')
    
    # a donde redirigir en caso de que no este logado
    login_url=reverse_lazy('usuario_app:login')
    
    def form_valid(self,form):
        usuario=self.request.user
        user=authenticate(
            username=usuario.username,
            password=form.cleaned_data['password1'],
        )
        if user:
            new_pass=form.cleaned_data['password2']
            new_pass2=form.cleaned_data['password3']
            if new_pass==new_pass2:
                usuario.set_password(new_pass)
                usuario.save()
        
        # Hacemos logout para que vuelva a logarse con la nueva pass   
        logout(self.request)
        return super(UpdatePass,self).form_valid(form)
    
        

bi_lms/templates/base/base.html
<!DOCTYPE html>
<html lang="es">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %} {% endblock title %}</title>
    {% load static %}

    <!-- Custom styles for this template-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="{% static 'css/estilos.css' %}" rel="stylesheet">
</head>


<body>
    <div id="header">
        <div id="inicial">
            <div id="logo">logo</div>
            <div id="show_menu">
                <img src=" {% static 'imagenes/menu.png' %} " alt=" " srcset=" "></div>
        </div>
        <div id="user">
            <div id="pater_avisos">
                <div id="avisos">
                    <a href=""><img src=" {% static 'imagenes/campana.png' %} " alt=" " srcset=" ">
                    </a>
                </div>
                <div id="burbuja_aviso">{{avisos}}</div>
            </div>
            <div id="pater_mensajes">
                <div id="uno">
                    <a href=""><img src=" {% static 'imagenes/comentario.png' %} " alt=" " srcset=" "></a>
                </div>
                <div id="burbuja_mensaje">{{mensajes}}</div>
            </div>

            <div>
                <a href=""><img src=" {% static 'imagenes/usuario.png' %} " alt=" " srcset=" ">
                </a>
            </div>
            <div>{{user.first_name}}</div>
            <div>
                <a class="linkito" href="{% url 'usuario_app:cambiarpass' %}">Actualizar contraseña
                </a>
            </div>
            <div id="cerrar">
                <a href="{% url 'usuario_app:logout' %}"><img src=" {% static 'imagenes/cerrar-sesion.png' %} " alt=" " srcset=" ">
                </a>
            </div>
        </div>


    </div>
    <div id="contenido">
        <div id="nav">
            <ul id="menu">
                <li class="iconos_menu {% if request.path == 'home' %}active{% endif %}">
                    <a class="linkito {% if request.path == 'home' %}active{% endif %}" href="{% url 'usuario_app:Home' %}"><img src=" {% static 'imagenes/icons8-página-principal-50.png' %} " alt=" " srcset=" ">Inicio</a>
                </li>
                <li id="mensajeria" class="iconos_menu {% if request.path == 'mensajeria' %}active{% endif %}">
                    <a class="linkito" href=""><img src=" {% static 'imagenes/icons8-mensaje-relleno-50.png' %} " alt=" " srcset=" ">Mensajeria</a><img src=" {% static 'imagenes/flecha-hacia-abajo-para-navegar.png' %} " alt="
                        " srcset=" ">
                    <ul>
                        <li>
                            <a href="">Bandeja de entrada</a></li>
                        <li>
                            <a href="">Enviados</a>
                        </li>
                        <li><a href="">Redactar</a></li>
                    </ul>
                </li>
                <li id="mensajeria" class="iconos_menu {% if request.path == 'formacion' %}active{% endif %}">
                    <a class="linkito" href=""><img src=" {% static 'imagenes/icons8-aprendizaje-50.png' %} " alt=" " srcset=" ">Formación</a><img src=" {% static 'imagenes/flecha-hacia-abajo-para-navegar.png' %} " alt=" " srcset=" ">
                    <ul>
                        <li>
                            <a href="">Cursos activos</a> </li>
                        <li><a href="">Test</a></li>
                        <li><a href="">Diplomas</a></li>

                    </ul>
                </li>
                <li id="mensajeria" class="iconos_menu {% if request.path == 'mi_actividad' %}active{% endif %}">
                    <a class="linkito" href=""><img src=" {% static 'imagenes/icons8-graph-60.png' %} " alt=" " srcset=" ">Actividad</a>
                </li>

            </ul>
        </div>
        <div id="main">
            {% block contenido %} {% endblock contenido %}
        </div>
        <div id="aside">aside</div>
    </div>
    <div id="footer">pie</div>
    <script src="{% static 'js/funciones.js' %} ">
    </script>
</body>

</html>

bi_lms/templates/usuario/cambiar_pass.html
{% extends "base/base.html" %} {% load static %} {% block title %}Cambiar Pass{% endblock title %}{% block contenido %}
<h1>Cambiar contraseña</h1>
<form action="" method="post">{% csrf_token %} {{form.as_p}} <button type="submit">Actualizar</button>
</form>{% endblock contenido %}

bi_lms/templates/usuario/home.html
{% extends "base/base.html" %} {% load static %} {% block title %}Inicio {% endblock title %}{% block contenido %}
<h1>Hola</h1> {% endblock contenido %}

bi_lms/templates/usuario/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
    <form method="post" class="">
        <fieldset>
            <legend>Login</legend>
            {% csrf_token %} {{form.as_table}}
            <button type="submit">Enviar</button>

        </fieldset>
    </form>
</body>

</html>